/* tslint:disable */
/* eslint-disable */
/**
 * Shin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ExtendParams
 */
export interface ExtendParams {

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    cardType?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    creditExtInfo?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    hbFqNum?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    hbFqSellerPercent?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    industryRefluxInfo?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    royaltyFreeze?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    specifiedSellerName?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    sysServiceProviderId?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    tcInstallmentOrderId?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    tradeComponentOrderId?: string | null;
}
